Repository integr8ly/delorean, pull requests merged in 2021-09, with the labels that each got.

#227 Fix openshift-ci-release - skip on patch releases
  cmd/openshiftCIRelease.go
Labels: lgtm, approved

#228 Add . to avoid jq exiting before it reads the whole input
  scripts/ocm/ocm.sh
Labels: lgtm, approved, ok-to-test

#226 Added an option to deploy an OSD trial cluster
  scripts/ocm/ocm.sh
Labels: lgtm, approved, ok-to-test

#224 feat: pipeline cleanup-aws
  cmd/cleanupAwsAccount.go
  cmd/cleanupAwsAccount_test.go
  go.mod
  go.sum
  pkg/utils/aws_mock.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/build.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/ec2query/unmarshal.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/jsonrpc.go
  vendor/github.com/aws/aws-sdk-go/private/protocol/jsonrpc/unmarshal_error.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/api.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/doc.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/errors.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/service.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/api.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/doc.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/elasticacheiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/errors.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/service.go
  vendor/github.com/aws/aws-sdk-go/service/elasticache/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/rds/api.go
  vendor/github.com/aws/aws-sdk-go/service/rds/customizations.go
  vendor/github.com/aws/aws-sdk-go/service/rds/doc.go
  vendor/github.com/aws/aws-sdk-go/service/rds/doc_custom.go
  vendor/github.com/aws/aws-sdk-go/service/rds/errors.go
  vendor/github.com/aws/aws-sdk-go/service/rds/rdsiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/rds/service.go
  vendor/github.com/aws/aws-sdk-go/service/rds/waiters.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/api.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/doc.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/errors.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/resourcegroupstaggingapiiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/resourcegroupstaggingapi/service.go
  vendor/github.com/integr8ly/cluster-service/LICENSE
  vendor/github.com/integr8ly/cluster-service/pkg/aws/client.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_ec2_route_table.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_ec2_security_group.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_ec2_subnet.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_ec2_vpc.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_ec2_vpc_peering.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_elasticache.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_elasticache_snapshot.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_rds.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_rds_snapshot.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_rds_subnet_group.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/manager_s3.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/moq_s3batchdeleteclient.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/tags.go
  vendor/github.com/integr8ly/cluster-service/pkg/aws/types.go
  vendor/github.com/integr8ly/cluster-service/pkg/clusterservice/clusterservice.go
  vendor/github.com/integr8ly/cluster-service/pkg/clusterservice/types.go
  vendor/github.com/integr8ly/cluster-service/pkg/errors/errors.go
  vendor/modules.txt
Labels: lgtm, approved

#230 added a way to install RHOAM on OSD trial cluster using addon-flow
  make/ocm.mk
  scripts/ocm/ocm.sh
Labels: lgtm, approved, needs-ok-to-test
